# Generated by Django 2.2.7 on 2020-02-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_obj',
            name='deadline',
            field=models.DateField(),
        ),
    ]
