# Generated by Django 2.2.7 on 2020-02-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200212_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_obj',
            name='explaination',
            field=models.TextField(blank=True, null=True),
        ),
    ]
