# Generated by Django 2.2.7 on 2020-02-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200212_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_obj',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='O', max_length=1),
        ),
    ]
